### ISSUE TITLE
CMS Edit breaks after upgrading EPiServer.CMS.UI to 11.4.2

### ISSUE THREAD

**Issue by DrewNull** [JohanPetersson/episerver-taxonomy#2]
Johan-- I'm having some trouble with any Episerver project that has been upgraded to EPiServer.CMS.UI 11.4.2 or higher... 

Steps to reproduce:

1. Start from an Episerver CMS project that has EPiServer.CMS.UI <11.4.2
2. Install Dodavinkeln.Taxonomy.0.5.0 (I'm using a local NuGet folder)
3. Upgrade EPiServer.CMS.UI to version 11.4.2 (or higher) -- EPiServer.CMS.UI.Core will also be updated
4. Ctrl+F5
5. Open CMS Edit
6. Observe that the screen is blank: 

![image](https://user-images.githubusercontent.com/1610135/41317607-52c81544-6e5b-11e8-8778-2f8f4efcc336.png)

A few notes:
- There are no JS console errors
- There are no network errors (no 4XXes or 5XXes)
- Nothing is logged in Event Viewer

I read through the following links but couldn't find any clues... 
- EPiServer.CMS.UI 11.4.2
  - [NuGet](https://nuget.episerver.com/package/?id=EPiServer.CMS.UI&v=11.4.2)
  - [Release Notes](https://world.episerver.com/documentation/Release-Notes/?versionFilter=11.4.2&packageFilter=EPiServer.CMS.UI&typeFilter=All)
- EPiServer.CMS.UI.Core 11.4.2
  - [NuGet](https://nuget.episerver.com/package/?id=EPiServer.CMS.UI.Core&v=11.4.2)
  - [Release Notes (none)](https://world.episerver.com/documentation/Release-Notes/?versionFilter=11.4.2&packageFilter=EPiServer.CMS.UI.Core&typeFilter=All)

The following files are checked out when I upgrade to 11.4.2: 
![image](https://user-images.githubusercontent.com/1610135/41317818-f366705e-6e5b-11e8-8d26-2025a8dc9a2e.png)

I haven't started digging into CMS.zip and Shell.zip, nor have I tried decompiling the DLLs. I'll probably start poking around there but was hoping you might have some insight first. Thanks!

**Comment by JohanPetersson** [comment]
Hi, this is a known issue and is caused by this bugfix https://world.episerver.com/support/Bug-list/bug/CMS-9245. Search area is missing from this add-on and Episerver is not handling that case. I will hopefully have a fix tomorrow. I'll keep you posted.

**Comment by DrewNull** [comment]
Got it, thanks Johan. Not sure if it helps, but the following line (21) in `TaxonomyComponent.cs` is where it fails: 

```this.PlugInAreas = new[] { PlugInArea.AssetsDefaultGroup };```

I tried setting the PlugInAreas to dashboard, which causes the dashboard to fail instead (makes sense). 

It doesn't look like the JS in `TaxonomyNavigationTree.js` is ever called. I put some console.logs in there and...nothing.

**Comment by JohanPetersson** [comment]
The widget is never loaded since it fails before that. It fails because I don't specify an search area in my component. Easy fix. Episerver will also fix this on their end, but I think I will beat them to it :)

**Comment by DrewNull** [comment]
Makes sense...thank you!

**Comment by JohanPetersson** [comment]
Now there is a new release 0.60. Please see 21d745351c099404d937417dd0c3cfa30faf14fb.

**Comment by DrewNull** [comment]
Johan--Just tested it locally and it works. Thank you!
